using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Form_For_Exercise_and_Lab_12
{
    public partial class Formfinal : Form
    {
        public Formfinal()
        {
            InitializeComponent();
            this.btnscissors.Click += (s, e) => { Scissors(); };
            this.btnrock.Click += (s, e) => { Rock(); };
            this.btnpaper.Click += (s, e) => { Paper(); };
        }

        private void Exit_Click(object sender, EventArgs e)
        {
            Close();
        }
        public void Scissors()
        {
            lblPlayer.Text = btnscissors.Text;
            //Get the contents in the Label box and convert them to int data.
            int vPlayer = ChangeStrToInt(btnscissors.Text);
            //Call the "Judge" method and compare the data entered by the player with the data generated by the computer. After that, display it to the "Result" box.
            lblResult.Text = Judge(vPlayer, PC());
        }
        public void Rock()
        {
            lblPlayer.Text = btnrock.Text;
            int vPlayer = ChangeStrToInt(btnrock.Text);
            lblResult.Text = Judge(vPlayer, PC());
        }
        public void Paper()
        {
            lblPlayer.Text = btnpaper.Text;
            int vPlayer = ChangeStrToInt(btnpaper.Text);
            lblResult.Text = Judge(vPlayer, PC());
        }
        
        /// <summary>
        /// Create a mouse click event to "convert a string to the corresponding int data" method.
        /// </summary>
        /// <param name="str">The content of the buttons that the player clicked.</param>
        /// <returns>Int data corresponding to those buttons.</returns>
        public int ChangeStrToInt(string str)
        {
            int n = 0;

            //Use the switch syntax to judge the input string.
            switch (str)
            {
                case "Scissors":
                    n = 1;
                    break;

                case "Rock":
                    n = 2;
                    break;

                case "Paper":
                    n = 3;
                    break;
                default:
                    throw new Exception("Unknown");
            }
            return n;
        }
        
        /// <summary>
        /// Create a method for PC to execute game events.
        /// </summary>
        /// <returns>Result value of PC's output.</returns>
        public int PC()
        {
            Random ran = new Random();
            int vPC = ran.Next(1, 4);
            string strPC = string.Empty;

            //Use the generated random values and the converted strings to judge the result.
            switch (vPC)
            {
                case 1:
                    strPC = "Scissors";
                    break;
                case 2:
                    strPC = "Rock";
                    break;
                case 3:
                    strPC = "Paper";
                    break;
                default:
                    throw new Exception("Unknown error! Unable to judge the event that the player clicked.");
            }
            lblPC.Text = strPC;//Display the results that PC's output.
            return vPC;
        }
        
        /// <summary>
        /// Compare the output values of the player and the PC to determine the outcome of this game.
        /// </summary>
        /// <param name="Player">Player's value</param>
        /// <param name="PC">PC's value</param>
        public string Judge(int Player, int PC)
        {
            //"1" refers to Scissors, "2" refers to Rock, "3" refers to Paper.
            //At a macro level, there are two judgment rules for "winning" results.
            //The value of the player is only 1 greater than the PC's; or, the value of the player is only 2 less than the PC's.
            int tmp = Player - PC;
            string judgedResult = string.Empty;
            if (tmp == 1 || tmp == -2)
                judgedResult = "You WIN!!!!";
            else if (tmp == 0)
                judgedResult = "→→→DARW←←←";
            else
                judgedResult = "You lose|XP";
            return judgedResult;
        }
        private void btnscissors_Click(object sender, EventArgs e)
        {
            Scissors();
        }

        private void btnrock_Click(object sender, EventArgs e)
        {
            Rock();
        }

        private void btnpaper_Click(object sender, EventArgs e)
        {
            Paper();
        }
    }
}